### ISSUE TITLE
dataset too large

### ISSUE THREAD

**Issue by akb13** [DeclareDesign/estimatr#24]
I'm using lm_robust on a dataset with 391,112 observations. My model includes 3 variables. I am receiving the following error: 

```
Error in lm_robust_helper(y = outcome, X = design_matrix, cluster = cluster,  : 
  SpMat::init(): requested size is too large; suggest to compile in C++11 mode or enable ARMA_64BIT_WORD
```
I have no issues when I use a dataset of reduced size (it runs with 78,000 observations but does not with 100,000).

**Comment by acoppock** [comment]
Can confirm: I get the same error with this code.

library(estimatr)
N <- 70000
df <- data.frame(Y = rbinom(N, 1, .5), X1 = rnorm(N), X2 = rnorm(N), X3 = rnorm(N))
lm_robust(Y ~ X1 + X2 + X3, data = df)

**Comment by lukesonnet** [comment]
This requires a migrate to cpp11 as I think you need to move over in order to increase the word size (re: https://stackoverflow.com/a/40592237/4257918 and http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2014-December/008295.html), so I've done just that.

I've pushed a branch to confirm this compiles on mac machines and added a test with a large data frame. Will confirm and close if it compiles on all platforms.

**Comment by graemeblair** [comment]
It sounded from Ashley that this is not fully resolved, is that the case?

**Comment by lukesonnet** [comment]
Well this specific error is resolved, and clustered ses work when `se_type = stata`. The problem is now that it hangs when `se_type = BM`, which we should look into resolving, but might not be possible.

That is more an issue of at finding any bottlenecks in the `BM` ses, which I've tried to do. I could open a new issue about performance on this issue.

**Comment by graemeblair** [comment]
Got it, thanks. Yes, open up an issue on that, but let's leave as low-priority (not for v1).
